services:
  devcontainer:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/base_app/app
    command: [ "python", "/base_app/app/cli_main.py" ]
    ports:
      - "80:80"
    devices:
      - "/dev/snd:/dev/snd"
