services:
  mkr:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ~/monkey-resonance:/monkey-resonance    
    devices:
      - "/dev/snd:/dev/snd"
    ports:
      - 8005:8005  
