services:
  devcontainer:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/base_app/app
    command: ["tail", "-f", "/dev/null"]
    devices:
      - "/dev/snd:/dev/snd"
