

services:
  devcontainer:
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - ../app:/base_app/app
      - ./in_container_options:/root/.vscode-server
      - ~/monkey-resonance/records:/records    
    entrypoint: [""]  
    command: ["tail", "-f", "/dev/null"]
    ports:
      - "8005:8005"
    devices:
      - "/dev/snd:/dev/snd"
